name: Build Kanim Explorer

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: src/KanimExplorer.sln
      Exe_Project_Name: src/KanimExplorer/KanimExplorer.csproj

    steps:
    # Checkout code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Configure Version
    - name: Configure Version
      run: |
        ./workflow-scripts/ConfigureVersion.ps1

    # Build and publish the application
    - name: Build & Publish
      run: dotnet publish $env:Exe_Project_name --configuration Release --version-suffix ci --framework net8.0-windows --os win -a x64 --sc false --output publish

    # Upload the publish output: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KanimExplorer_${{env.CI_VersionPrefix}}-ci_x64
        path: publish
